config/routes.rb
Rails.application.routes.draw do
  resources :users
  get '/users/edit', to: 'users#edit'
  get '/courses/instructor', to: 'courses#instructor'
  get '/allenrollments', to: 'enrollments#allenrollments'
  get '/allWaitlists', to: 'waitlists#allWaitlist'
  get '/myCourseEnrollments', to: 'enrollments#myCourseEnrollments'
  get '/myCourseWaitlists', to: 'waitlists#myCourseWaitlists'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#logout'
  resources :waitlists
  resources :enrollments
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
end

app/controllers/waitlists_controller.rb
class WaitlistsController < ApplicationController
  before_action :set_waitlist, only: %i[ show edit update destroy ]

  # GET /waitlists or /waitlists.json
  def index
    user_id = current_user.id.to_s
    @waitlists = Waitlist.where(student_id: user_id)
  end

  def allWaitlist
    @waitlists = Waitlist.all
  end
  # GET /waitlists/1 or /waitlists/1.json
  def show
  end

  # GET /waitlists/new
  def new
    @waitlist = Waitlist.new
  end

  # GET /waitlists/1/edit
  def edit
  end

  def myCourseWaitlists
    @courses = Course.where(instructor_id: current_user.id.to_s)
  end

  # POST /waitlists or /waitlists.json
  def create
    @waitlist = Waitlist.new(waitlist_params)
    course = Course.find_by(name: waitlist_params["course_id"])

    enrollingStudent = User.find_by(id: waitlist_params["student_id"].to_i)

    p enrollingStudent

    if(!enrollingStudent or enrollingStudent["identifier"] != "1")
      redirect_to '/waitlists/new', notice: "Student with id #{waitlist_params["student_id"]} doesn't exist"
      return
    end


    if(current_user.id.to_s != waitlist_params["student_id"] and current_user.identifier == "1")
      redirect_to '/waitlists/new', notice: 'You are not allowed to waitlist other students'
      return
    end
    

    if(current_user.id.to_s != course["instructor_id"] and current_user.identifier == "2")
      redirect_to '/waitlists/new', notice: 'You are not allowed to waitlist students in courses that are not yours'
      return
    end

    isEnrolled = Enrollment.where(course_id: waitlist_params["course_id"], student_id: waitlist_params["student_id"]).count
    isWaitlist = Waitlist.where(course_id: waitlist_params["course_id"], student_id: waitlist_params["student_id"]).count
    if(isEnrolled == 1 || isWaitlist == 1 )
      redirect_to '/waitlists/new', notice: 'You already enrolled or waitlisted for this course'
      return
    end


    noOfWaitlist = Waitlist.where(course_id: waitlist_params["course_id"]).count
    waitlistCapacity = course["waitlist_capacity"]

    respond_to do |format|
      if @waitlist.save
        if(noOfWaitlist+1 == waitlistCapacity)
          course.update(status: 'CLOSED')
        end
        format.html { redirect_to waitlist_url(@waitlist), notice: "Waitlist was successfully created." }
        format.json { render :show, status: :created, location: @waitlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waitlists/1 or /waitlists/1.json
  def update
    respond_to do |format|
      if @waitlist.update(waitlist_params)
        format.html { redirect_to waitlist_url(@waitlist), notice: "Waitlist was successfully updated." }
        format.json { render :show, status: :ok, location: @waitlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitlists/1 or /waitlists/1.json
  def destroy
    @waitlist.destroy

    course = Course.find_by(name: @waitlist["course_id"])
    courseStatus = course["status"]

    noOfWaitlist = Waitlist.where(course_id: @waitlist["course_id"]).count

    if(courseStatus == "CLOSED")
      course.update(status: 'WAITLIST')
    end

    respond_to do |format|
      format.html { redirect_to waitlists_url, notice: "Waitlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waitlist
      @waitlist = Waitlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def waitlist_params
      params.require(:waitlist).permit(:course_id, :student_id)
    end
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/waitlists/_form.html.erb
<%= form_with(model: waitlist) do |form| %>
  <% if waitlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(waitlist.errors.count, "error") %> prohibited this waitlist from being saved:</h2>

      <ul>
        <% waitlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <% if Course.where(status: "WAITLIST").count == 0 %>
    <h1>There are no waitlist courses available</h1>
  <% else %>
    <div>
      <%= form.label :course_id, style: "display: block" %>
      <%= select("waitlist", "course_id", Course.where(status: "WAITLIST").collect{ |c| [ c.name, c.name] }, :required => true) %>
    </div>

    <div>
      <%= form.label :student_id, style: "display: block" %>

      <% if logged_in? %>
        <% if current_user.identifier == "1" %>
          <%= form.text_field :student_id, value: current_user.id %>
        <%end%>
      <%end%>

      <% if logged_in? %>
        <% if current_user.identifier == "2" or current_user.identifier == "0" %>
          <%= form.text_field :student_id %>
        <%end%>
      <%end%>

    </div>

  <div>
    <%= form.submit "Enter Waitlist" %>
  </div>

  <% end %>

<% end %>

app/views/waitlists/_waitlist.html.erb
<div id="<%= dom_id waitlist %>">
  <p>
    <strong>Course:</strong>
    <%= waitlist.course_id %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= waitlist.student_id %>
  </p>

</div>

app/views/waitlists/allWaitlist.html.erb
<h1>Waitlists</h1>

<div id="waitlists">
  <% @waitlists.each do |waitlist| %>
    <%= render waitlist %>
    <p>
      <%= link_to "Show this waitlist", waitlist %>
    </p>
  <% end %>
</div>

<%= link_to "New waitlist", new_waitlist_path %>

app/views/waitlists/edit.html.erb
<h1>Editing waitlist</h1>

<%= render "form", waitlist: @waitlist %>

<br>

<div>
  <%= link_to "Show this waitlist", @waitlist %> |
  <%= link_to "Back to waitlists", waitlists_path %>
</div>

app/views/waitlists/index.html.erb
<h1>Waitlists</h1>

<div id="waitlists">
  <% @waitlists.each do |waitlist| %>
    <%= render waitlist %>
    <p>
      <%= link_to "Show this waitlist", waitlist %>
    </p>
  <% end %>
</div>

<%= link_to "New waitlist", new_waitlist_path %>

app/views/waitlists/myCourseWaitlists.html.erb
<h1>Waitlists in my class</h1>

<div id="waitlists">
  <% @courses.each do |course| %>
    
    <% waitlists = Waitlist.where(course_id: course.name) %>

        <% waitlists.each do |waitlist| %>

            <p>
                <strong>Course:</strong>
                
                <%= waitlist.course_id %>
            </p>

            <p>
                <strong>Student:</strong>
                <%= waitlist.student_id %>
            </p>
            <p>
                <%= link_to "Show this waitlist", waitlist %>
            </p>

        <% end %>

   
  <% end %>
</div>

app/views/waitlists/new.html.erb
<h1>New waitlist</h1>

<%= render "form", waitlist: @waitlist %>

<br>

<div>
  <%= link_to "Back to waitlists", waitlists_path %>
</div>

app/views/waitlists/show.html.erb
<%= render @waitlist %>

<div>
  <%= link_to "Edit this waitlist", edit_waitlist_path(@waitlist) %> |
  <%= link_to "Back to waitlists", waitlists_path %>
  <% if current_user.identifier == "0" or current_user.id.to_i == @waitlist.student_id.to_i %>
    <%= button_to "Remove waitlist", @waitlist, method: :delete %>
  <% end %>
</div>