config/routes.rb
Rails.application.routes.draw do
  resources :users
  get '/users/edit', to: 'users#edit'
  get '/courses/instructor', to: 'courses#instructor'
  get '/allenrollments', to: 'enrollments#allenrollments'
  get '/allWaitlists', to: 'waitlists#allWaitlist'
  get '/myCourseEnrollments', to: 'enrollments#myCourseEnrollments'
  get '/myCourseWaitlists', to: 'waitlists#myCourseWaitlists'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#logout'
  resources :waitlists
  resources :enrollments
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true
  validates :email_id, presence: true, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ifNotLoggedin, only: %i[ new , create]

  def index
    if(current_user.identifier != "0")
      redirect_to '/', notice: "#{current_user.username} you are not allowed to view all"
    end
    @users = User.all
  end

  def new
    @user=User.new
  end

  def show
    if(current_user.id.to_s != params[:id] and current_user.identifier != "0")
      redirect_to '/', notice: "#{current_user.username} you are not allowed to view other's profile"
    end
    @user = User.find(params[:id])
  end

  def edit
    if(current_user.id.to_s != params[:id] and current_user.identifier != "0")
      redirect_to '/', notice: "#{current_user.username} you are not allowed to change other's profile"
    end
    @user = User.find(params[:id])
  end

  def create
   @user = User.create(params.require(:user).permit(:username,
   :password,:email_id,:identifier, :phone_no, :department, :date_of_birth, :major))
   p current_user
   if !current_user
      session[:user_id] = @user.id
   end
   redirect_to root_path, notice: "User Created"
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(params.require(:user).permit(:username,
        :password,:email_id,:identifier, :phone_no, :department, :date_of_birth, :major))
        format.html { redirect_to user_url(@user), notice: "user was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])

    # If student is deleted, all enrollemnts and waitlists should be deleted and course should be updated
    if (@user.identifier == "1")
      Waitlist.where(student_id: @user.id.to_s ).destroy_all
      enrollments = Enrollment.where(student_id: @user.id.to_s )
      enrollments.each do |enrollment|

        # Once enrollment is dropped update the enrollment with waitlisted student and update the course status
        
        enrollment.destroy

        course_id = enrollment["course_id"]
        student_id = enrollment["student_id"]

        noOfWaitlist = Waitlist.where(course_id: enrollment["course_id"]).count
        course = Course.find_by(name: enrollment["course_id"])
        courseCapacity = course["capacity"]
        waitlistCapacity = course["waitlist_capacity"]

        if(noOfWaitlist > 0)
          # Move Eaitlist sutdents to enroll
          firstWaitlits = Waitlist.where(course_id: enrollment["course_id"]).limit(1).order('created_at desc')
          firstWaitlistStudent = ""
          firstWaitlits.each do |firstWaitlit|
            firstWaitlistStudent = firstWaitlit["student_id"]
            firstWaitlit.destroy
            newEnrollement = Enrollment.new(course_id: course_id, student_id: firstWaitlistStudent)
            newEnrollement.save
            noOfWaitlist = noOfWaitlist -1
          end

        end

        noOfEnrollments = Enrollment.where(course_id: enrollment["course_id"]).count

        if(course["status"] == "CLOSED" || course["status"] == "WAITLIST")
          #Move it to waitlist
          if(noOfEnrollments == courseCapacity && waitlistCapacity > noOfWaitlist)
            course.update(status: 'WAITLIST')
          elsif(noOfEnrollments < courseCapacity)
            course.update(status: 'OPEN')
          end
          #move it to open
        end

      end


    end

    # # If instructor is deleted, all courses, enrollemnts and waitlists should be deleted
    if (@user.identifier == "2")
      coursesForThisInstructor = Course.where(instructor_id: @user.id.to_s)
      coursesForThisInstructor.each do |course|
        course_id = course["name"]
        Enrollment.where(course_id: course_id ).destroy_all
        Waitlist.where(course_id: course_id ).destroy_all
        course.destroy
      end
    end


    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email_id, :phone_no, :department, :date_of_birth, :major)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if current_user.identifier == "0" %>
<h1>Edit User</h1>
<% end %>

<%= form_for @user, html: {id: :sign_up_form_id } do |f|%>

  <% if @user.identifier == "0" %>
    <%= f.label :username, id: :user_name_label %><br>
    <%= f.text_field :username, :required => true%><br>
    <%= f.label :phone_no, id: :phone_no_label %><br>
    <%= f.text_field :phone_no%><br>
  <% else %>
    <%= f.label :username, id: :user_name_label %><br>
    <%= f.text_field :username, :required => true%><br>
    <%= f.label :email_id, id: :email_id_label %><br>
    <%= f.email_field :email_id, :required => true%><br>
    <%= f.label :password, id: :password_label %><br>
    <%= f.password_field :password%><br>

    <% if @user.identifier == "1" %>
    <%= f.label :phone_no, id: :phone_no_label %><br>
    <%= f.text_field :phone_no%><br>
    <%= f.label :date_of_birth, "Date Of Birth (Format should be in MM/DD/YYYY)", id: :date_of_birth_label %><br>
    <%= f.text_field :date_of_birth%><br>
    <%= f.label :major, id: :major_label %><br>
    <%= f.text_field :major%><br>

    <% elsif @user.identifier == "2" %>
    <%= f.label :department, id: :department_label %><br>
    <%= f.text_field :department%><br>

    <% end %>
  <% end %>
  <%= f.submit %>
<%end%>



<script type="text/javascript">


  function doValidations(e) {

  var user_name_label = document.getElementById('user_name_label');
  var user_username = document.getElementById('user_username').value;

  var email_id_label = document.getElementById('email_id_label');
  var user_email_id = document.getElementById('user_email_id').value;

  var phone_no_label = document.getElementById('phone_no_label');
  if(phone_no_label) {
    var user_phone_no = document.getElementById('user_phone_no').value;
  }

  var department_label = document.getElementById('department_label');
  if(department_label) {
    var user_department = document.getElementById('user_department').value;
  }

  var date_of_birth_label = document.getElementById('date_of_birth_label');
  if(date_of_birth_label) {
    var user_date_of_birth = document.getElementById('user_date_of_birth').value;
  }

  var major_label = document.getElementById('major_label');
  if(major_label) {
    var user_major = document.getElementById('user_major').value;
  }


    if(user_name_label && !user_username) {
      alert("Username cannot be empty");
      e.preventDefault();
    }

    if(email_id_label && !user_email_id) {
      alert("Email cannot be empty");
      e.preventDefault();
    }

    if(phone_no_label && !user_phone_no) {
      alert("Phone No cannot be empty");
      e.preventDefault();
    }

    if(department_label && !user_department) {
      alert("Department cannot be empty");
      e.preventDefault();
    }

    if(date_of_birth_label && !user_date_of_birth) {
      alert("Date of birth cannot be empty");
      e.preventDefault();
    }

    if(major_label && !user_major) {
      alert("Major cannot be empty");
      e.preventDefault();
    }


    var email_idd = document.getElementById('user_email_id').value;
    console.log("adfsd", email_idd)
    if ( !(/[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z0-9]+/.test(email_idd)) ) {
      alert("Please enter valid email id");
      e.preventDefault();
    }

  e.preventDefault();
  }

  var form_button = document.getElementById('sign_up_form_id');
  form_button.addEventListener("submit", doValidations, false);
</script>

app/views/users/_instructor.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>User Type: </strong>
    Instructor
  </p>
  <p>
    <strong>User Name:</strong>
    <%= user.username %>
  </p>
  <p>
    <strong>Email ID:</strong>
    <%= user.email_id %>
  </p>
  <p>
    <strong>Department:</strong>
    <%= user.department %>
  </p>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>User Type: </strong>
     <% if user.identifier == "1" %>
    Student
    <% end %>
    <% if user.identifier == "2" %>
    Instructor
    <% end %>
    <% if user.identifier == "0" %>
    Admin
    <% end %>
  </p>
  <p>
    <strong>User ID:</strong>
    <%= user.id %>
  </p><p>
    <strong>User Name:</strong>
    <%= user.username %>
  </p>
  <p>
    <strong>Email ID:</strong>
    <%= user.email_id %>
  </p>
  <% if user.identifier == "1" %>
  <p>
    <strong>Phone No:</strong>
    <%= user.phone_no %>
  </p>
  <% end %>
  <% if user.identifier == "1" %>
  <p>
    <strong>Date Of Bith:</strong>
    <%= user.date_of_birth %>
  </p>
  <% end %>
  <% if user.identifier == "1" %>
  <p>
    <strong>Major:</strong>
    <%= user.major %>
  </p>
  <% end %>
  <% if user.identifier == "2" %>
  <p>
    <strong>Department:</strong>
    <%= user.department %>
  </p>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> 
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<div id="users">
  <% @users.each do |user| %>
    <% if user.identifier == "1" or  user.identifier == "2" %>
      <%= render user %><p>
      <%= link_to "Show this user", user %>
    </p>
    <% end %>
    
  <% end %>
</div>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<% if current_user %>
<h1>Create Student or Instructor</h1>
<% else %>

<h1>Sign Up</h1>
<% end %>

<%= form_for @user, html: {id: :sign_up_form_id } do |f|%>
  <p>
    <b>Who are you?</b>
    <%= f.radio_button :identifier, '1' %> Student<br />
    <%= f.radio_button :identifier, '2' %> Instructor<br />
  </p>
  <%= f.label :username, id: :user_name_label %><br>
  <%= f.text_field :username, :required => true%><br>
  <%= f.label :email_id, id: :email_id_label %><br>
  <%= f.email_field :email_id, :required => true%><br>
  <%= f.label :password, id: :password_label %><br>
  <%= f.password_field :password, :required => true%><br>
  <%= f.label :phone_no, id: :phone_no_label %><br>
  <%= f.text_field :phone_no%><br>
  <%= f.label :department, id: :department_label %><br>
  <%= f.text_field :department%><br>
  <%= f.label :date_of_birth, "Date Of Birth (Format should be in MM/DD/YYYY)", id: :date_of_birth_label %> <br>
  <%= f.text_field :date_of_birth%><br>
  <%= f.label :major, id: :major_label %><br>
  <%= f.text_field :major%><br>
  
  <%= f.submit %>
<%end%>



<script type="text/javascript">
  function hideAllFields(e) {
    user_name_label.style.display = "none";
    user_username.style.display = "none";
  }

  var user_identifier_1 = document.getElementById('user_identifier_1');
  var user_identifier_2 = document.getElementById('user_identifier_2');

  var user_name_label = document.getElementById('user_name_label');
  var user_username = document.getElementById('user_username');

  var email_id_label = document.getElementById('email_id_label');
  var user_email_id = document.getElementById('user_email_id');

  var password_label = document.getElementById('password_label');
  var user_password = document.getElementById('user_password');

  var phone_no_label = document.getElementById('phone_no_label');
  var user_phone_no = document.getElementById('user_phone_no');

  var department_label = document.getElementById('department_label');
  var user_department = document.getElementById('user_department');

  var date_of_birth_label = document.getElementById('date_of_birth_label');
  var user_date_of_birth = document.getElementById('user_date_of_birth');

  var major_label = document.getElementById('major_label');
  var user_major = document.getElementById('user_major');


  var submit_button = document.querySelector("input[type='submit']");


  user_name_label.style.display = "none";
  user_username.style.display = "none";
  email_id_label.style.display = "none";
  user_email_id.style.display = "none";
  password_label.style.display = "none";
  user_password.style.display = "none";
  phone_no_label.style.display = "none";
  user_phone_no.style.display = "none";
  department_label.style.display = "none";
  user_department.style.display = "none";
  date_of_birth_label.style.display = "none";
  user_date_of_birth.style.display = "none";
  major_label.style.display = "none";
  user_major.style.display = "none";
  submit_button.style.display = "none";

  function showOnlyStudentFields (e) {
      user_name_label.style.display = "block";
      user_username.style.display = "block";
      email_id_label.style.display = "block";
      user_email_id.style.display = "block";
      password_label.style.display = "block";
      user_password.style.display = "block";
      phone_no_label.style.display = "block";
      user_phone_no.style.display = "block";
      department_label.style.display = "none";
      user_department.style.display = "none";
      date_of_birth_label.style.display = "block";
      user_date_of_birth.style.display = "block";
      major_label.style.display = "block";
      user_major.style.display = "block";
  submit_button.style.display = "block";
  }

  function showOnlyInstructorFields(e) {
      user_name_label.style.display = "block";
      user_username.style.display = "block";
      email_id_label.style.display = "block";
      user_email_id.style.display = "block";
      password_label.style.display = "block";
      user_password.style.display = "block";
      phone_no_label.style.display = "none";
      user_phone_no.style.display = "none";
      department_label.style.display = "block";
      user_department.style.display = "block";
      date_of_birth_label.style.display = "none";
      user_date_of_birth.style.display = "none";
      major_label.style.display = "none";
      user_major.style.display = "none";
  submit_button.style.display = "block";
  }

  user_identifier_1.addEventListener("click", showOnlyStudentFields, false);
  user_identifier_2.addEventListener("click", showOnlyInstructorFields, false);

  function doValidations(e) {
    var student = user_identifier_1.checked;
    var instructor = user_identifier_2.checked;
    
    if(student) {
      var user_phone_no = document.getElementById('user_phone_no').value;
      var user_date_of_birth = document.getElementById('user_date_of_birth').value;
      var user_major = document.getElementById('user_major').value;
      if(!user_phone_no || !user_date_of_birth || !user_major) {
        alert("Please enter all the fields");
        e.preventDefault();
      }
    }

    if(instructor) {
      var user_department = document.getElementById('user_department').value;
      if(!user_department) {
        alert("Please enter all the fields");
        e.preventDefault();
      }
    }

    var email_id = document.getElementById('user_email_id').value;
    if ( !(/[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z0-9]+/.test(email_id)) ) {
      alert("Please enter valid email id");
      e.preventDefault();
    }
  }

  var form_button = document.getElementById('sign_up_form_id');
  form_button.addEventListener("submit", doValidations, false);
</script>

app/views/users/show.html.erb
<%= render @user %>

<div>
  <% if current_user.identifier == "0" %>
    <%= link_to "Edit this user", edit_user_path(@user) %> 
    <% if @user.identifier != "0" %>
    <%= button_to "Delete User", @user, method: :delete %>
    <% end %>
  <% end %>
</div>