config/routes.rb
Rails.application.routes.draw do
  resources :users
  get '/users/edit', to: 'users#edit'
  get '/courses/instructor', to: 'courses#instructor'
  get '/allenrollments', to: 'enrollments#allenrollments'
  get '/allWaitlists', to: 'waitlists#allWaitlist'
  get '/myCourseEnrollments', to: 'enrollments#myCourseEnrollments'
  get '/myCourseWaitlists', to: 'waitlists#myCourseWaitlists'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#logout'
  resources :waitlists
  resources :enrollments
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord

  validates :course_id, presence: true
  validates :student_id, presence: true
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    user_id = current_user.id.to_s
    @enrollments = Enrollment.where(student_id: user_id)
  end

  def allenrollments
    @enrollments = Enrollment.all
  end


  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create

    @enrollment = Enrollment.new(enrollment_params)
    course = Course.find_by(name: enrollment_params["course_id"])

    enrollingStudent = User.find_by(id: enrollment_params["student_id"].to_i)

    if(!enrollingStudent or enrollingStudent["identifier"].to_i != 1)
      redirect_to '/enrollments/new', notice: "Student with id #{enrollment_params["student_id"]} doesn't exist"
      return
    end

    # if logged in student is not the one enrolling

    if(current_user.id.to_s != enrollment_params["student_id"] and current_user.identifier == "1")
      redirect_to '/enrollments/new', notice: 'You are not allowed to enroll other students'
      return
    end
    
    # instructor should not be able to enroll studnets for other courses

    if(current_user.id.to_s != course["instructor_id"] and current_user.identifier == "2")
      redirect_to '/enrollments/new', notice: 'You are not allowed to enroll students in courses that are not yours'
      return
    end


    isEnrolled = Enrollment.where(course_id: enrollment_params["course_id"], student_id: enrollment_params["student_id"]).count
    if(isEnrolled == 1)
      redirect_to '/enrollments/new', notice: 'Already enrolled into this course'
      return
    end

    # course_id in Enrollment is name in Course

    noOfEnrollments = Enrollment.where(course_id: enrollment_params["course_id"]).count
    noOfWaitlist = Waitlist.where(course_id: enrollment_params["course_id"]).count
    courseCapacity = course["capacity"]
    waitlistCapacity = course["waitlist_capacity"]

    if(noOfEnrollments >=  courseCapacity) 
      redirect_to '/courses', notice: 'This course is full'
      return
    end


    respond_to do |format|
      if @enrollment.save
        # condition to close the course
        if(noOfEnrollments+1 == courseCapacity && (noOfWaitlist == waitlistCapacity) )
          course.update(status: 'CLOSED')
        elsif (noOfEnrollments+1 == courseCapacity && (noOfWaitlist < waitlistCapacity) )
          course.update(status: 'WAITLIST')
        end
        format.html { redirect_to enrollment_url(@enrollment), notice: "You are enrolled succesfully." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def myCourseEnrollments
    @courses = Course.where(instructor_id: current_user.id.to_s)
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    enrollment = @enrollment
    @enrollment.destroy

    course_id = enrollment["course_id"]
    student_id = enrollment["student_id"]

    noOfWaitlist = Waitlist.where(course_id: enrollment["course_id"]).count
    course = Course.find_by(name: enrollment["course_id"])
    courseCapacity = course["capacity"]
    waitlistCapacity = course["waitlist_capacity"]

    if(noOfWaitlist > 0)
      # Move Eaitlist sutdents to enroll
      firstWaitlits = Waitlist.where(course_id: enrollment["course_id"]).limit(1).order('created_at desc')
      firstWaitlistStudent = ""
      firstWaitlits.each do |firstWaitlit|
        firstWaitlistStudent = firstWaitlit["student_id"]
        firstWaitlit.destroy
        newEnrollement = Enrollment.new(course_id: course_id, student_id: firstWaitlistStudent)
        newEnrollement.save
        noOfWaitlist = noOfWaitlist -1
      end

    end

    noOfEnrollments = Enrollment.where(course_id: enrollment["course_id"]).count

    if(course["status"] == "CLOSED" || course["status"] == "WAITLIST")
      #Move it to waitlist
      if(noOfEnrollments == courseCapacity && waitlistCapacity > noOfWaitlist)
        course.update(status: 'WAITLIST')
      elsif(noOfEnrollments < courseCapacity)
        course.update(status: 'OPEN')
      end
      #move it to open
    end

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Unenrolled student." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:course_id, :student_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
    <strong>Course:</strong>
    
    <%= enrollment.course_id %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= enrollment.student_id %>
  </p>

</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- change this -->
  <% if Course.where(status: "OPEN").count == 0 %>
    <h1>There are no open courses available</h1>
  <% else %>
    <div>
      <%= form.label :course_id, style: "display: block" %>
      <%= select("enrollment", "course_id", Course.where(status: "OPEN").collect{ |c| [ c.name, c.name] }, :required => true) %>
    </div>

    <div>
      <%= form.label :student_id, style: "display: block" %>

      <% if logged_in? %>
        <% if current_user.identifier == "1" %>
          <%= form.text_field :student_id, value: current_user.id %>
        <%end%>
      <%end%>

      <% if logged_in? %>
        <% if current_user.identifier == "2" or current_user.identifier == "0" %>
          <%= form.text_field :student_id %>
        <%end%>
      <%end%>

    </div>

    <div>
      <%= form.submit "Enroll" %>
    </div>

  <% end %>
<% end %>

app/views/enrollments/allenrollments.html.erb
<h1>All Enrollments</h1>

<div id="enrollments">
  <% @enrollments.each do |enrollment| %>
    <%= render enrollment %>
    <p>
      <%= link_to "Show this enrollment", enrollment %>
    </p>
  <% end %>
</div>

<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<h1>Enrollments</h1>

<div id="enrollments">
  <% @enrollments.each do |enrollment| %>
    <%= render enrollment %>
    <p>
      <%= link_to "Show this enrollment", enrollment %>
    </p>
  <% end %>
</div>

<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/myCourseEnrollments.html.erb
<h1>Enrollments in my class</h1>

<div id="enrollments">
  <% @courses.each do |course| %>
    
    <% enrollments = Enrollment.where(course_id: course.name) %>

        <% enrollments.each do |enrollment| %>

            <p>
                <strong>Course:</strong>
                
                <%= enrollment.course_id %>
            </p>

            <p>
                <strong>Student:</strong>
                <%= enrollment.student_id %>
            </p>
            <p>
                <%= link_to "Show this enrollment", enrollment %>
            </p>

        <% end %>

   
  <% end %>
</div>

<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<%= render @enrollment %>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>