config/routes.rb
Rails.application.routes.draw do
  resources :users
  get '/users/edit', to: 'users#edit'
  get '/courses/instructor', to: 'courses#instructor'
  get '/allenrollments', to: 'enrollments#allenrollments'
  get '/allWaitlists', to: 'waitlists#allWaitlist'
  get '/myCourseEnrollments', to: 'enrollments#myCourseEnrollments'
  get '/myCourseWaitlists', to: 'waitlists#myCourseWaitlists'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#logout'
  resources :waitlists
  resources :enrollments
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  def instructor
    @courses = Course.where(instructor_id: current_user["id"])
  end

  # GET /courses/new
  def new
    if session[:user_id] != nil
      if current_user.identifier == "1"
        redirect_to '/', notice: "Sorry you are not authorized to create a course"
      end
    end
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    
    course = Course.find_by(id: params[:id])
    if(current_user.id.to_s != course["instructor_id"] and current_user.identifier == "2")
      redirect_to '/courses', notice: 'You are not allowed to edit the courses that are not yours'
      return
    end

    if(current_user.identifier == "1")
      redirect_to '/courses', notice: 'You are not allowed to edit the courses'
      return
    end

  end

  # POST /courses or /courses.json
  def create

    if current_user.identifier == "2" and course_params["instructor_id"].to_i != current_user.id
      redirect_to '/courses/new', notice: "Sorry you are not authorized to create a course for other instructor"
      return
    end
    
    @course = Course.new(course_params)

    #Set course capacity to OPEN when created
    @course["status"] = "OPEN"
  
    instructor = User.find_by(id: course_params["instructor_id"].to_i)
    instructor_name = instructor["username"]
    @course["instructor_name"] = instructor_name

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    course_id = @course["name"]
    Enrollment.where(course_id: course_id ).destroy_all
    Waitlist.where(course_id: course_id ).destroy_all

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :description, :instructor_name, :weekday_1, :weekday_2, :start_time, :end_time, :course_code, :capacity, :waitlist_capacity, :status, :room, :instructor_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= course.description %>
  </p>

  <p>
    <strong>Instructor name:</strong>
    <%= course.instructor_name %>
  </p>

  <p>
    <strong>Instructor ID:</strong>
    <%= course.instructor_id %>
  </p>

  <p>
    <strong>Weekday 1:</strong>
    <%= course.weekday_1 %>
  </p>

  <p>
    <strong>Weekday 2:</strong>
    <%= course.weekday_2 %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= course.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= course.end_time %>
  </p>

  <p>
    <strong>Course code:</strong>
    <%= course.course_code %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= course.capacity %>
  </p>

  <p>
    <strong>Waitlist capacity:</strong>
    <%= course.waitlist_capacity %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= course.status %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= course.room %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with model: @course, id: "create_course_form"  do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :instructor_id, 'Instructor ID', style: "display: block" %>
    <% if logged_in? %>
      <% if current_user.identifier == "2" %>
        <%= form.text_field :instructor_id, value: current_user.id %>
      <%end%>
      <% if current_user.identifier == "0" %>
        <%= form.text_field :instructor_id %>
      <%end%>
    <%end%>
  </div>

  <div>
    <%= form.label :weekday_1, style: "display: block" %>
    <%= form.select :weekday_1, ['MON', 'TUE', 'WED', 'THU', 'FRI']%>
  </div>

  <div>
    <%= form.label :weekday_2, style: "display: block" %>
    <%= form.select :weekday_2, ['','MON', 'TUE', 'WED', 'THU', 'FRI']%>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.text_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.text_field :end_time %>
  </div>

  <div>
    <%= form.label :course_code, style: "display: block" %>
    <%= form.text_field :course_code %>
  </div>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.label :waitlist_capacity, style: "display: block" %>
    <%= form.number_field :waitlist_capacity %>
  </div>

  <div>
    <%= form.label :room, style: "display: block" %>
    <%= form.text_field :room %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


<script type="text/javascript">

  var dic = {
    "MON" : 1,
    "TUE" : 2,
    "WED" : 3,
    "THU" : 4,
    "FRI" : 5,
    "" : 6
  }


  function validateDays(e) {
    var course_weekday_1 = document.getElementById('course_weekday_1').value;
    var course_weekday_2 = document.getElementById('course_weekday_2').value;
    var w1 = dic[course_weekday_1];
    var w2 = dic[course_weekday_2];
    if(w1 > w2) {
      alert("Weekday 2 should be after Weekday 1");
      e.preventDefault();
    }
    if(course_weekday_1 == course_weekday_2) {
      alert("Both Weekday 1 and Weekday 2 cannot be same");
      e.preventDefault();
    }
  }

  var st1 = null;
  var st2 = null;

  function startTimeValidation(e) {
    var course_start_time_value = document.getElementById('course_start_time').value;
    var course_start_time_value_arr = course_start_time_value.split(":");
    st1 = parseInt(course_start_time_value_arr[0]);
    st2 = parseInt(course_start_time_value_arr[1]);
    if((st1 < 0 || st1 > 23) || (st2 < 0 || st2 > 59)){
      alert(" Start Date format should be a 24 hr format in HH:MM between 00:00 to 23:59");
      e.preventDefault();
      return;
    }
  }

  function endTimeValidation(e) {
    var course_end_time_value = document.getElementById('course_end_time').value;
    var course_end_time_value_arr = course_end_time_value.split(":");
    var et1 = parseInt(course_end_time_value_arr[0]);
    var et2 = parseInt(course_end_time_value_arr[1]);

    console.log("et111", et1);

    if( et1 < 0 || et1 > 23 || et2 < 0 || et2 > 59 || isNaN(et1) || isNaN(et2) ){
      alert("End Date format should be a 24 hr format in HH:MM between 00:00 to 23:59");
      e.preventDefault();
      return;
    } else if((et1 == st1 && et2 <= st2) || et1 < st1 || isNaN(et1) || isNaN(et2) ) {
      alert("End time should be after start time");
      e.preventDefault();
      return;
    }
  }

  function validateRoom(e) {
    var course_room = document.getElementById('course_room').value;
    if(!course_room){
      if(course_room != "0") {
        alert("Room cannot be empty");
        e.preventDefault();
      }
    }
  }

  function validateCourseCode(e) {
    var course_course_code = document.getElementById('course_course_code').value;
    if((course_course_code.length != 6) || !(/[a-zA-Z][a-zA-Z][a-zA-Z]/.test(course_course_code.substring(0,3))) || !(/[0-9][0-9][0-9]/.test(course_course_code.substring(3,6))) ) {
      alert("Course code is not in correct format");
      e.preventDefault();
    }
  }

  function doValidations(e) {
    startTimeValidation(e);
    endTimeValidation(e);
    validateDays(e);
    validateRoom(e);
    validateCourseCode(e);
  }

  

  var form_button = document.getElementById('create_course_form');
  form_button.addEventListener("submit", doValidations, false);

</script>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
    <p>
      <%= link_to "Show this course", course %>
    </p>
  <% end %>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/instructor.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
    <p>
      <%= link_to "Show this course", course %>
    </p>
  <% end %>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <% if current_user.identifier == "0" or current_user.id == @course.instructor_id.to_i %>
    <%= button_to "Destroy this course", @course, method: :delete %>
    <%= link_to "Edit this course", edit_course_path(@course) %> 
  <% end %>
</div>